### ISSUE TITLE
Undefined property: stdClass::$v2City

### ISSUE THREAD

**Issue by dlink** [ExtensionsStore/Addressvalidator#6]
Hello,

I'm testing Addressvalidator with our Magento Enterprise 1.14.2.0 software, running on RedHat release 6.7, with PHP 5.5.30.  And I'm getting the following error in the extensions_store_addressvalidator.log, when I click [continue] after filling in the Billing Address.

2016-11-22T18:08:15+00:00 dev1 DEBUG (7): Notice: Undefined property: stdClass::$v2City  in /home/dlink/web/app/code/community/ExtensionsStore/Addressvalidator/Model/Service/Fedex.php on line 186

Thank you for any help resolving this.

**Comment by ExtensionsStore** [comment]
The latest release in Master has fix for this. See commit 1030e283635a2814fbc2a0f7db24cbcecdb60417

**Comment by dlink** [comment]
Dig thanks.  I made the same fix.
