### ISSUE TITLE
Magento 1.9.3 Popup doesn't appear

### ISSUE THREAD

**Issue by RCady** [ExtensionsStore/Addressvalidator#8]
After clicking continue the popup window never appears on the page. It completes the request and doesn't move forward.

The request returns the new valid addresses, but after receiving them they are not displayed in the popup.

**Comment by RCady** [comment]
I've narrowed it down to this:

```
        	onCreate : function(req, transport, json){
        		if (batriggered || satriggered){
                    console.log('test');
            		if (batriggered){
            			if (savingBilling){
            				transport.abort();
            				return;
            			}
            			batriggered = false;
            			savingBilling = true;
            			req.url += '?form_id=billing_address';
            		} else if (satriggered) {
            			if (savingShipping){
            				transport.abort();
            				return;            				
            			}
            			satriggered = false;
            			savingShipping = true;
            			req.url += '?form_id=shipping_address';
            		}
        			
        		}
        	}
```

The variables `batriggered` and `satriggered` don't exist on the page

**Comment by RCady** [comment]
I've figured it out!

The issue is caused when the an address object within the response from the Ajax call contains a null value. In the following code is where the error stops the execution of the rest of the method. This function is within the `validateAddress` function inside `addressvalidator.js`

```
for (var i = 0; i < length; i++) {

    var address = results[i];

    var street = (typeof address.street !== 'string' && address.street.length > 1) ? address.street.join(', ') : address.street;
    var city = (typeof address.city !== 'string' && address.city.length > 1) ? address.city.join(', ') : address.city;

    var addressAr = [street, city, address.region, address.postcode, address.country];
    addressAr = addressAr.filter(function (n) {
        return n != undefined
    });

    var label = addressAr.join(', ');
    
    var checked = (i == 0) ? 'checked="checked"' : '';

    radios += '<li><label><input type="radio" class="radio" '+checked+' name="address" value="' + i + '" /> ' + label + '</label></li>';

}
```


In my config I had a primary AND secondary validation service enabled. My secondary service caused this issue.

I don't have a solution for an error like this yet, but in the server file it would be a good idea to not send a response that contains null values. We can log this error and send a notification to the administrator or not validate the address at all and tell them to contact their administrator.

**Comment by ExtensionsStore** [comment]
If the popup doesn't appear, most likely there's a exception or error on the server.

**Comment by RCady** [comment]
That's what was going on. I figured it out.
